replicaCount: 1

image:
  repository: "auth"
  tag: "dev"
  pullPolicy: IfNotPresent
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://db.dev.svc.cluster.local:5432/bankdb"
  - name: SPRING_DATASOURCE_USERNAME
    value: "bankuser"
service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

livenessProbe:
  path: /actuator/health
readinessProbe:
  path: /actuator/health

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false

httpRoute:
  enabled: true
  parentRefs:
    - name: bank-gateway
      namespace: dev
  hostnames:
    - auth.dev.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

