replicaCount: 1

image:
  repository: "discovery"
  tag: "dev"
  pullPolicy: IfNotPresent
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://db.dev.svc.cluster.local:5432/bankdb"
  - name: SPRING_DATASOURCE_USERNAME
    value: "bankuser"
service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

livenessProbe:
  path: /actuator/health
readinessProbe:
  path: /actuator/health

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false

httpRoute:
  enabled: false

containerPort: 8761
resources: {}
