spring:
  application:
    name: auth-server

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics,env,configprops"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  observations:
    enable:
      all: true

management.tracing:
  enabled: true
  sampling:
    probability: 1.0
management.zipkin:
  tracing:
    endpoint: http://zipkin.dev.svc.cluster.local:9411/api/v2/spans

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: auth_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_schema
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: auth-server
