apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  {{- range .Values.gateway.listeners }}
- name: {{ .name }}
  port: {{ .port }}
  protocol: {{ .protocol }}
  {{- if .hostname }}
hostname: {{ .hostname }}
  {{- end }}
allowedRoutes:
  {{- toYaml .allowedRoutes | nindent 8 }}
  {{- end }}
