apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    {{- range $l := .Values.gateway.listeners }}
    - name: {{ $l.name }}
      port: {{ $l.port }}
      protocol: {{ $l.protocol }}
      {{- if $l.hostname }}
      hostname: {{ $l.hostname }}
      {{- end }}
      allowedRoutes:
        {{- toYaml $l.allowedRoutes | nindent 8 }}
    {{- end }}
