replicaCount: 1
persistence:
  size: 5Gi
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoprovision:
  enabled: true
  topics:
    - name: notifications
      partitions: 1
      replicationFactor: 1
    - name: exchange-events
      partitions: 1
      replicationFactor: 1
