replicaCount: 1

image:
  repository: "accounts"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

livenessProbe:
  path: /actuator/health
readinessProbe:
  path: /actuator/health

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false

httpRoute:
  enabled: false
