apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: controller
      port: 9093
      targetPort: 9093
    - name: internal
      port: 9092
      targetPort: 9092
